// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmCjNyECojRlxOFMbpDHUIyK7JRtfFC8g',
    appId: '1:604852875090:web:54d932c3cf8ec1aad3948b',
    messagingSenderId: '604852875090',
    projectId: 'ticketmanager-31154',
    authDomain: 'ticketmanager-31154.firebaseapp.com',
    storageBucket: 'ticketmanager-31154.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAduI3eVLYwigGiq4OP7I_4CoL_Sk8KQs',
    appId: '1:604852875090:android:34b8afe3f419df18d3948b',
    messagingSenderId: '604852875090',
    projectId: 'ticketmanager-31154',
    storageBucket: 'ticketmanager-31154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwp5IchL05lLCLB9nTLZ9Z7hQOvrmkxBo',
    appId: '1:604852875090:ios:0d1d863493f79aa2d3948b',
    messagingSenderId: '604852875090',
    projectId: 'ticketmanager-31154',
    storageBucket: 'ticketmanager-31154.appspot.com',
    iosBundleId: 'com.example.managerTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmCjNyECojRlxOFMbpDHUIyK7JRtfFC8g',
    appId: '1:604852875090:web:b803a4a2ef285ed4d3948b',
    messagingSenderId: '604852875090',
    projectId: 'ticketmanager-31154',
    authDomain: 'ticketmanager-31154.firebaseapp.com',
    storageBucket: 'ticketmanager-31154.appspot.com',
  );
}
